li = [1,2,6,2,3,0]
li.append(2)
print(li, "append")
li.extend([3,4,10])
print(li , "extend")
li.insert(2,10)
print(li , "insert")
li.remove(0)
print(li , "remove")
li.pop()
print(li , "pop")
li.index(3)
print(li , "index")
li.count(2)
print(li , "count")
li.sort()
print(li , "sort")
li.sort(reverse=True)
print(li , "sort")
li.sort()
print(li , "sort")
li.reverse()
print(li , "revese")
li.copy()
print(li , "copy")
li.clear()
print(li , "clear")
